### ISSUE TITLE
Sitemap Index with relative URLs and Google

### ISSUE THREAD

**Issue by s-diez** [aimeos/ai-controller-jobs#17]
Google, at least through its search console, does not accept relative URLs in the index sitemap as locations for the individual sitemaps.

The specification https://www.sitemaps.org/protocol.html#locdef does require a full URL with protocol for `loc` of an `url` entry. For sitemap index it is not exactly defined, but I would guess the same definition applies.

The index files generated through aimeos only include the basename of the file.

**Comment by aimeos** [comment]
There seems to be an issue with the different TYPO3 scripts for running the scheduler tasks: https://github.com/aimeos/aimeos-typo3/issues/104

**Comment by s-diez** [comment]
I don't think this is the issue here. The actual URLs for categories and products are generated just fine in my case.

The problem is in the sitemap index file. How can the following code ever generate more then something like `aimeos-sitemap-1.xml.gz`: https://github.com/aimeos/ai-controller-jobs/blob/6e8feecbc14282a0dcc409ec2b8c2cd722a5d9ae/controller/jobs/templates/catalog/export/sitemap-index-standard.php#L18
but Google seems to need a full absolute URL with protocol.

**Comment by aimeos** [comment]
OK, that's true. I'm unsure if we can use `$this->url(...)` for that case because we don't know where the files are located and which URL should be used

**Comment by s-diez** [comment]
I agree. Maybe a configuration variable?

**Comment by aimeos** [comment]
Seems to be the only option and it must be configurable in the TYPO3 scheduler task too

**Comment by s-diez** [comment]
PR is merged. Thanks.
