### ISSUE TITLE
coupon code import issue (not working)

### ISSUE THREAD

**Issue by amiraghyan99** [aimeos/ai-controller-jobs#29]
Hello @aimeos 
Can you help me 
I have issue with import coupon
when I run this command   `php artisan aimeos:jobs coupon/import/csv/code`
its returned error 
but I didn't change anything 
 and import coupon code default 
[Coupons Aimeos  - Sheet1 - Coupons Aimeos  - Sheet1 (2).csv](https://github.com/aimeos/ai-controller-jobs/files/6392742/Coupons.Aimeos.-.Sheet1.-.Coupons.Aimeos.-.Sheet1.2.csv)

**Comment by amiraghyan99** [comment]
Process (PID "292181") failed with status "256"

**Comment by aimeos** [comment]
Most likely because your file doesn't contain the coupon ID in the file name, i.e. it must be `<couponid>.csv`.
Otherwise it's not possible to know to which coupon provider configuration the codes should be added to.

**Comment by amiraghyan99** [comment]
yes I fix it thanks
and how can i add it to cron job?
to make it work
thanks

**Comment by amiraghyan99** [comment]
automaticlly

**Comment by amiraghyan99** [comment]
when I Importe coupon when call command manually

**Comment by aimeos** [comment]
Please read: https://aimeos.org/docs/latest/laravel/setup/#cronjobs
