### ISSUE TITLE
CSV product import image previews

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-controller-jobs#32]
Currently when importing products via the CSV job without specifying image previews, no previews are generated. Looking at https://github.com/aimeos/ai-controller-jobs/blob/676104a0d3865e5216689a9a55660b9b219fc6d6/controller/common/src/Controller/Common/Product/Import/Csv/Processor/Media/Standard.php#L233 it seems that thumbs should be generated - however, this never happens, because the $force parameter in the `scale()` function call is not true.

Is this desired behaviour or is the `$force` parameter missing here?

**Comment by aimeos** [comment]
The easiest way to fix that is passing the `force` parameter like you suggest and I don't think this has negative consequences.
The real problem may be that `date( 'Y-m-d H:i:s', $fs->time( $item->getUrl() ) ) < $item->getTimeModified()` doesn't return `false` for new items

**Comment by nvindice** [comment]
Agreed. So should I make a PR with the `force` parameter?

**Comment by aimeos** [comment]
Yes, please :-)
