### ISSUE TITLE
Trying to import "selection" type products, but it doesn't work

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-controller-jobs#39]
Hello Aimeos!
I'm trying to import "selection" type products, but it doesn't work for me at all.

**Mapping:**

'item' => array(
	0 => 'product.code',
	1 => 'product.label',
	2 => 'product.type',
	3 => 'product.status',
),
...
...
'product' => array(
	15 => 'product.code',
),

**CSV:**
![subproderror](https://user-images.githubusercontent.com/61547701/150690462-76224f02-6fe5-4f2f-a590-f4aa30f029d0.jpg)

For the "selection" product, the "subproductcode" column contains the following content:
**YRBQ1I43CM
YRBQ1I48CM
YRBQ1I53CM**

Can you help me?

**Comment by Ameeko** [comment]
Thanks for the reply.
Unfortunately, there is no error message in the log panel.
I attached the CSV and mapping.
Status after import:
![aimeos-import-error](https://user-images.githubusercontent.com/61547701/150858646-20f802d8-3b85-4dfc-aeca-9de5dce4ea9a.jpg)

[test-aimeos.csv](https://github.com/aimeos/ai-controller-jobs/files/7928622/test-aimeos.csv)
[mapping-aimeos.txt](https://github.com/aimeos/ai-controller-jobs/files/7928623/mapping-aimeos.txt)

**Comment by aimeos** [comment]
The type code of selection products is `select`, not `selection`

**Comment by Ameeko** [comment]
It works.
Thank you very much.
