### ISSUE TITLE
Merge images for "selection" products

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-controller-jobs#41]
Hello Aimeos!
I imported "selection" type products.

For example:
- Main selection product (**blue.jpg** because of the article list)
 - - Subproduct1 (Blue, size1, **blue.jpg**)
 - - Subproduct2 (Blue, size2, **blue.jpg**)
 - - Subproduct3 (Blue, size3, **blue.jpg**)

 - - Subproduct4 (Red, size1, **red.jpg**)
 - - Subproduct5 (Red, size2, **red.jpg**)
 - - Subproduct6 (Red, size3, **red.jpg**)

 - - Subproduct7 (Green, size1, **green.jpg**)
 - - Subproduct8 (Green, size2, **green.jpg**)
 - - Subproduct9 (Green, size3, **green.jpg**)

In this case, when I open the main selection product, I will see 10 images (4x blue.jpg, 3x red.jpg and 3x green.jpg).

What is the best way to see each image only once (1x blue.jpg, 1x red.jpg and 1x green.jpg)?

**Comment by aimeos** [comment]
The easiest way is to attach the image only to the first sub-product with the color attribute, i.e.
- Subproduct1: blue.jpg
- Subproduct4: red.jpg
- Subproduct7: green.jpg
