### ISSUE TITLE
Payment mail template not editable

### ISSUE THREAD

**Issue by nollm** [aimeos/ai-controller-jobs#45]
Is there a possibility to adapt the mail template?
Currently it is so minimized, that you can't edit anything or have any overview what happended there.
https://github.com/aimeos/ai-controller-jobs/blob/master/templates/order/email/delivery/html.php
Do you use a tool or something else to unminimize it?
Thank's for help!

**Comment by aimeos** [comment]
The PHP file is generated from the MJML (https://mjml.io/) source:
https://github.com/aimeos/ai-controller-jobs/blob/master/templates/order/email/delivery/html.mjml

**Comment by nollm** [comment]
Nice tool! Works for me.

**Comment by nollm** [comment]
Is there a possibility to show images of services and the product?

**Comment by aimeos** [comment]
In theory yes, but external images are often blocked by email clients and using inline images increases the size of the e-mails drastically.

**Comment by nollm** [comment]
Ok, thanks for your help!
