### ISSUE TITLE
Timeframe missing from Import

### ISSUE THREAD

**Issue by mbrather** [aimeos/ai-controller-jobs#46]
https://github.com/aimeos/ai-controller-jobs/blob/6e4564cb47fb4be3097be65920c1ee7dca0a0428/src/Controller/Jobs/Stock/Import/Csv/Standard.php#L453-L455

Version 2022.10

The timeframe in the CSV file is ignored.
Please add "->setTimeframe( $this->val( $entry, 4 ) )" after setDateBack.

**Comment by aimeos** [comment]
Thanks for the hint!
Can you create a PR with the missing method call?

**Comment by mbrather** [comment]
I created a PR for you. Hope I did right.

**Comment by aimeos** [comment]
Merged

**Comment by mbrather** [comment]
Thank you. Can you backport it to version 2022.10 though?

**Comment by aimeos** [comment]
Done. Use aimeos/ai-controller-jobs:2022.10.x-dev

**Comment by mbrather** [comment]
Thank you very much.
