### ISSUE TITLE
Order from auto-renewed subscriptions will have empty payment status

### ISSUE THREAD

**Issue by Physikbuddha** [aimeos/ai-controller-jobs#49]
When an active subscription is automatically renewed by the respective cronjob, a new order is created.

However, due to a bug in `aimeos/ai-controller-jobs/src/Controller/Jobs/Subscription/Process/Renew/Standard.php`, the payment status will never be set correctly and stays at `---`. This also means that no invoice will be generated and sent.

Trying to manually set the payment status in the Aimeos backend is not possible, because the invoice number is a mandatory field and needs to be filled out. However, this should not be in the user's domain of responsibility.

The reason this is happening is, because the Renew controller's `process()` function fails to update the order after the payment service has set the payment status.

See this screenshot for reference:

![2024-10-30 13_30_16](https://github.com/user-attachments/assets/60c2bdcb-9b61-449d-8e84-2e97f6c8c101)

The order is saved in line 557. However, line 561 is calling the `renew()` function of the payment provider who sets the payment status. However, this change will never be saved. I tried copying the "save order" command from line 557 to line 567. This line has been added by me and is not present in the actual Aimeos product. By adding this line, the order is saved and displayed in the backend correctly. Also sending out the invoice is working as expected.

**Comment by aimeos** [comment]
Thank you for your bug report!
The issue has been fixed with this commit: https://github.com/aimeos/ai-controller-jobs/commit/3a66be1eb7ee8f6482318a7bb29bd4c73d406c3d
The fix is also available if you run `composer req aimeos/ai-controller-jobs:2024.10.x-dev`. Can you check if it works as expected now?
