### ISSUE TITLE
Documentation of `controller/jobs/product/export/sitemap/domains`

### ISSUE THREAD

**Issue by s-diez** [aimeos/ai-controller-jobs#8]
The configuration option `controller/jobs/product/export/sitemap/domains` is not documented.
As far as I understand it should be at https://aimeos.org/docs/Configuration/Core/controller/jobs/product/export/sitemap/domains and listed under https://aimeos.org/docs/Configuration/Core/controller/jobs/product.

**Comment by aimeos** [comment]
Fixed by https://github.com/aimeos/ai-controller-jobs/pull/10
