### ISSUE TITLE
Typo in config key in sitemap export

### ISSUE THREAD

**Issue by s-diez** [aimeos/ai-controller-jobs#9]
In Aimeos\Controller\Jobs\Product\Export\Sitemap\Standard the configuration for the domains is queried with the key `domains`, but in the switch statement to resolve this to `controller/jobs/product/export/sitemap/domains` the case `domain` is checked.
https://github.com/aimeos/ai-controller-jobs/blob/6dd4586c91a104dd46103e1a75e9679092a465f8/controller/jobs/src/Controller/Jobs/Product/Export/Sitemap/Standard.php#L349
https://github.com/aimeos/ai-controller-jobs/blob/6dd4586c91a104dd46103e1a75e9679092a465f8/controller/jobs/src/Controller/Jobs/Product/Export/Sitemap/Standard.php#L403

**Comment by s-diez** [comment]
As the pull request is already merged I'll close this issue.

**Comment by aimeos** [comment]
Your patch has been merged into 2018.10.x-dev and will be part of the next release. You can test and use this branch in the meantime by adding this line to your composer.json:

```"aimeos/ai-controller-jobs": "2018.10.x-dev"```
